version: 0.2

phases:
  install:
   commands:
     - echo Entering install phase...
     - echo Nothing to do now
  build:
    commands:
     - echo Build started on `date`
     - ./gradlew build
     - mv target/app.war ROOT.war
artifacts:
  type: zip
  files:
    - 'build/libs/*.war'
