version: 0.2

phases:
  install:
   commands:
     - echo Entering install phase...
     - echo Nothing to do now
  build:
    commands:
     - echo Build started on `date`
     - ./gradlew build
artifacts:
  files:
    - target/orbnet.jar
  discard-paths: yes
