spring:
  datasource:
    url: jdbc:mysql://orb-freeradius-1.cyg6ao0nnff3.ap-south-1.rds.amazonaws.com:3306/radius
    username: root
    password: ByzRsK28pW
  mail:
    username: info@orbvpn.com
    password: nsoojhxetlcyjtgm

oauth:
  google:
    client-ids: 159610264827-8qoc1ai11afi5lsn556mbs1rfd8123io.apps.googleusercontent.com
  facebook:
    app-id: 838668077053807
    app-secret: fc420c2366504297e88ce941395c7f13

stripe:
  api:
    secret-key: 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
    public-key: pk_live_51J05ChKYm0whdaYrUOh4ue2598MXLr5xf34iGvunlv3wKAoLRxEvZt25spARozGV6EtcxvgGIiwWAh54sfnaObl900u49NQaJ6
    webhook-secret: whsec_qBAL6SqSy6VtZiJIr2Mun0XVfYHALgZF