spring:
  datasource:
    url: jdbc:mysql://orb-radius.cjij5m9kax4h.eu-central-1.rds.amazonaws.com:3306/radius
    username: root
    password: ByzRsK28pW
  mail:
    username: info@orbvpn.com
    password: nsoojhxetlcyjtgm

oauth:
  google:
    client-ids: 159610264827-8qoc1ai11afi5lsn556mbs1rfd8123io.apps.googleusercontent.com
  facebook:
    app-id: 1148726045646863
    app-secret: cc5724526559fd8501f77edb67e85d9b