server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/radius
    username: root
    password: ByzRsK28pW
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: testorbdev1234@gmail.com
    password: testorb1234
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true



application:
  website-url: http://example.com

jwt:
  secret: secret
  issuer: iss
  expirationMillis: 1000000000000
  refreshMillis: 100000000000
  resetPasswordSecret: secret
  resetPasswordExpirationMillis: 1000000000000
graphql:
  servlet:
    exception-handlers-enabled: true

stripe:
  api:
    secret-key: sk_test_51IuGKuKHM8iu6lnJ0fEKCdca9sA2DF8K4dOMcHSBoHk4ljCbbH5aEYSRuCPkCpdZNUeWSq4Cut5T19Yyl1vVpFuE00IKjpvPvU
    public-key: pk_test_51IuGKuKHM8iu6lnJeXPVpGSNucHcJKMvMWYGartWgEFAj67M3DkgFZVVUORjiRHoQ5nao2EyB7EOk2gTUYTi5YtK00Yrmkfkzk
    webhook-secret: whsec_8GpHy7eDtKlMgThkDWPfSm7dougQspxb
