server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/radius
    username: root
    password: ByzRsK28pW
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: testorbdev1234@gmail.com
    password: testorb1234
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true



application:
  website-url: http://example.com

jwt:
  secret: secret
  issuer: iss
  expirationMillis: 1000000000000
  refreshMillis: 100000000000
  resetPasswordSecret: secret
  resetPasswordExpirationMillis: 1000000000000
graphql:
  servlet:
    exception-handlers-enabled: true
  datetime:
    scalars:
      zone-conversion-enabled: true

stripe:
  api:
    secret-key: sk_test_51IuGKuKHM8iu6lnJ0fEKCdca9sA2DF8K4dOMcHSBoHk4ljCbbH5aEYSRuCPkCpdZNUeWSq4Cut5T19Yyl1vVpFuE00IKjpvPvU
    public-key: pk_test_51IuGKuKHM8iu6lnJeXPVpGSNucHcJKMvMWYGartWgEFAj67M3DkgFZVVUORjiRHoQ5nao2EyB7EOk2gTUYTi5YtK00Yrmkfkzk
    webhook-secret: whsec_8GpHy7eDtKlMgThkDWPfSm7dougQspxb

paypal:
  client-id: AQLq6ju_TV-1obwarCVgpoOFkEYuZzG0f4fWMvZ3W9OlO1Pzv1yviba1DWWkFaqMUQ_YUdoguIfxkj-f
  secret: EDS3YYiH3P7u7Rnwq5tdjH0_JAfR4RDSPVAtydY3cCbUtnnNC9FFQyRW2FkZ0yuLR5-e7nkTwbp-KfOp
  mode: sandbox

oauth:
  google:
    client-ids: 159610264827-8qoc1ai11afi5lsn556mbs1rfd8123io.apps.googleusercontent.com
  facebook:
    app-id: 1148726045646863
    app-secret: cc5724526559fd8501f77edb67e85d9b
