spring:
  datasource:
    url: jdbc:mysql://orb-radius.cjij5m9kax4h.eu-central-1.rds.amazonaws.com:3306/radius
    username: root
    password: ByzRsK28pW
  mail:
    username: info@orbvpn.com
    password: nsoojhxetlcyjtgm

oauth:
  facebook:
    app-id: 2998455443765493
    app-secret: 690acb522724caa05e0c70083c1333dc