spring:
  datasource:
    url: jdbc:mysql://orb-radius.cjij5m9kax4h.eu-central-1.rds.amazonaws.com:3306/radius
    username: root
    password: ByzRsK28pW

oauth:
  google:
    client-ids: 159610264827-8qoc1ai11afi5lsn556mbs1rfd8123io.apps.googleusercontent.com
  facebook:
    app-id: 838668077053807
    app-secret: fc420c2366504297e88ce941395c7f13