server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/radius
    username: root
    password: ByzRsK28pW
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: testorbdev1234@gmail.com
    password: testorb1234
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true


application:
  website-url: http://example.com

jwt:
  secret: secret
  issuer: iss
  expirationMillis: 1000000000000
  refreshMillis: 100000000000
  resetPasswordSecret: secret
  resetPasswordExpirationMillis: 1000000000000

